//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM リレーションシップのメタデータ

[assembly: EdmRelationshipAttribute("Sample01RModel", "ModuleUser", "Module", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MarimoCompile_ver1._0.MvcApplication1.MvcApplication1.Models.Module), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MarimoCompile_ver1._0.MvcApplication1.MvcApplication1.Models.User))]
[assembly: EdmRelationshipAttribute("Sample01RModel", "UnitModule", "Unit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MarimoCompile_ver1._0.MvcApplication1.MvcApplication1.Models.Unit), "Module", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MarimoCompile_ver1._0.MvcApplication1.MvcApplication1.Models.Module))]

#endregion

namespace MarimoCompile_ver1._0.MvcApplication1.MvcApplication1.Models
{
    #region コンテキスト
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    public partial class Sample01REntities : ObjectContext
    {
        #region コンストラクター
    
        /// <summary>
        /// アプリケーション構成ファイルの 'Sample01REntities' セクションにある接続文字列を使用して新しい Sample01REntities オブジェクトを初期化します。
        /// </summary>
        public Sample01REntities() : base("name=Sample01REntities", "Sample01REntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい Sample01REntities オブジェクトを初期化します。
        /// </summary>
        public Sample01REntities(string connectionString) : base(connectionString, "Sample01REntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい Sample01REntities オブジェクトを初期化します。
        /// </summary>
        public Sample01REntities(EntityConnection connection) : base(connection, "Sample01REntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分メソッド
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<Module> Modules
        {
            get
            {
                if ((_Modules == null))
                {
                    _Modules = base.CreateObjectSet<Module>("Modules");
                }
                return _Modules;
            }
        }
        private ObjectSet<Module> _Modules;
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<Unit> Units
        {
            get
            {
                if ((_Units == null))
                {
                    _Units = base.CreateObjectSet<Unit>("Units");
                }
                return _Units;
            }
        }
        private ObjectSet<Unit> _Units;
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<TypeData> TypeDatas
        {
            get
            {
                if ((_TypeDatas == null))
                {
                    _TypeDatas = base.CreateObjectSet<TypeData>("TypeDatas");
                }
                return _TypeDatas;
            }
        }
        private ObjectSet<TypeData> _TypeDatas;

        #endregion

        #region AddTo メソッド
    
        /// <summary>
        /// Modules EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToModules(Module module)
        {
            base.AddObject("Modules", module);
        }
    
        /// <summary>
        /// Users EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Units EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToUnits(Unit unit)
        {
            base.AddObject("Units", unit);
        }
    
        /// <summary>
        /// TypeDatas EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToTypeDatas(TypeData typeData)
        {
            base.AddObject("TypeDatas", typeData);
        }

        #endregion

    }

    #endregion

    #region エンティティ
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sample01RModel", Name="Module")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Module : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい Module オブジェクトを作成します。
        /// </summary>
        /// <param name="id">id プロパティの初期値。</param>
        /// <param name="name">Name プロパティの初期値。</param>
        /// <param name="numData">NumData プロパティの初期値。</param>
        public static Module CreateModule(global::System.Int32 id, global::System.String name, global::System.Int32 numData)
        {
            Module module = new Module();
            module.id = id;
            module.Name = name;
            module.NumData = numData;
            return module;
        }

        #endregion

        #region 単純なプロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PassWord
        {
            get
            {
                return _PassWord;
            }
            set
            {
                OnPassWordChanging(value);
                ReportPropertyChanging("PassWord");
                _PassWord = StructuralObject.SetValidValue(value, true, "PassWord");
                ReportPropertyChanged("PassWord");
                OnPassWordChanged();
            }
        }
        private global::System.String _PassWord;
        partial void OnPassWordChanging(global::System.String value);
        partial void OnPassWordChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true, "Location");
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Detail
        {
            get
            {
                return _Detail;
            }
            set
            {
                OnDetailChanging(value);
                ReportPropertyChanging("Detail");
                _Detail = StructuralObject.SetValidValue(value, true, "Detail");
                ReportPropertyChanged("Detail");
                OnDetailChanged();
            }
        }
        private global::System.String _Detail;
        partial void OnDetailChanging(global::System.String value);
        partial void OnDetailChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumData
        {
            get
            {
                return _NumData;
            }
            set
            {
                OnNumDataChanging(value);
                ReportPropertyChanging("NumData");
                _NumData = StructuralObject.SetValidValue(value, "NumData");
                ReportPropertyChanged("NumData");
                OnNumDataChanged();
            }
        }
        private global::System.Int32 _NumData;
        partial void OnNumDataChanging(global::System.Int32 value);
        partial void OnNumDataChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Latest
        {
            get
            {
                return _Latest;
            }
            set
            {
                OnLatestChanging(value);
                ReportPropertyChanging("Latest");
                _Latest = StructuralObject.SetValidValue(value, true, "Latest");
                ReportPropertyChanged("Latest");
                OnLatestChanged();
            }
        }
        private global::System.String _Latest;
        partial void OnLatestChanging(global::System.String value);
        partial void OnLatestChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true, "Type");
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();

        #endregion

        #region ナビゲーション プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sample01RModel", "ModuleUser", "User")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("Sample01RModel.ModuleUser", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("Sample01RModel.ModuleUser", "User", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sample01RModel", "UnitModule", "Unit")]
        public EntityCollection<Unit> Units
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Unit>("Sample01RModel.UnitModule", "Unit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Unit>("Sample01RModel.UnitModule", "Unit", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sample01RModel", Name="TypeData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TypeData : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい TypeData オブジェクトを作成します。
        /// </summary>
        /// <param name="id">id プロパティの初期値。</param>
        /// <param name="dataType">DataType プロパティの初期値。</param>
        public static TypeData CreateTypeData(global::System.Int32 id, global::System.String dataType)
        {
            TypeData typeData = new TypeData();
            typeData.id = id;
            typeData.DataType = dataType;
            return typeData;
        }

        #endregion

        #region 単純なプロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DataType
        {
            get
            {
                return _DataType;
            }
            set
            {
                OnDataTypeChanging(value);
                ReportPropertyChanging("DataType");
                _DataType = StructuralObject.SetValidValue(value, false, "DataType");
                ReportPropertyChanged("DataType");
                OnDataTypeChanged();
            }
        }
        private global::System.String _DataType;
        partial void OnDataTypeChanging(global::System.String value);
        partial void OnDataTypeChanged();

        #endregion

    }
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sample01RModel", Name="Unit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Unit : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい Unit オブジェクトを作成します。
        /// </summary>
        /// <param name="id">id プロパティの初期値。</param>
        /// <param name="typeDataId">TypeDataId プロパティの初期値。</param>
        public static Unit CreateUnit(global::System.Int32 id, global::System.Int32 typeDataId)
        {
            Unit unit = new Unit();
            unit.id = id;
            unit.TypeDataId = typeDataId;
            return unit;
        }

        #endregion

        #region 単純なプロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Unit1
        {
            get
            {
                return _Unit1;
            }
            set
            {
                OnUnit1Changing(value);
                ReportPropertyChanging("Unit1");
                _Unit1 = StructuralObject.SetValidValue(value, true, "Unit1");
                ReportPropertyChanged("Unit1");
                OnUnit1Changed();
            }
        }
        private global::System.String _Unit1;
        partial void OnUnit1Changing(global::System.String value);
        partial void OnUnit1Changed();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TypeDataId
        {
            get
            {
                return _TypeDataId;
            }
            set
            {
                OnTypeDataIdChanging(value);
                ReportPropertyChanging("TypeDataId");
                _TypeDataId = StructuralObject.SetValidValue(value, "TypeDataId");
                ReportPropertyChanged("TypeDataId");
                OnTypeDataIdChanged();
            }
        }
        private global::System.Int32 _TypeDataId;
        partial void OnTypeDataIdChanging(global::System.Int32 value);
        partial void OnTypeDataIdChanged();

        #endregion

        #region ナビゲーション プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sample01RModel", "UnitModule", "Module")]
        public EntityCollection<Module> Modules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Module>("Sample01RModel.UnitModule", "Module");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Module>("Sample01RModel.UnitModule", "Module", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sample01RModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい User オブジェクトを作成します。
        /// </summary>
        /// <param name="id">id プロパティの初期値。</param>
        /// <param name="idName">idName プロパティの初期値。</param>
        /// <param name="nickName">NickName プロパティの初期値。</param>
        public static User CreateUser(global::System.Int32 id, global::System.String idName, global::System.String nickName)
        {
            User user = new User();
            user.id = id;
            user.idName = idName;
            user.NickName = nickName;
            return user;
        }

        #endregion

        #region 単純なプロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idName
        {
            get
            {
                return _idName;
            }
            set
            {
                OnidNameChanging(value);
                ReportPropertyChanging("idName");
                _idName = StructuralObject.SetValidValue(value, false, "idName");
                ReportPropertyChanged("idName");
                OnidNameChanged();
            }
        }
        private global::System.String _idName;
        partial void OnidNameChanging(global::System.String value);
        partial void OnidNameChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PassWord
        {
            get
            {
                return _PassWord;
            }
            set
            {
                OnPassWordChanging(value);
                ReportPropertyChanging("PassWord");
                _PassWord = StructuralObject.SetValidValue(value, true, "PassWord");
                ReportPropertyChanged("PassWord");
                OnPassWordChanged();
            }
        }
        private global::System.String _PassWord;
        partial void OnPassWordChanging(global::System.String value);
        partial void OnPassWordChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NickName
        {
            get
            {
                return _NickName;
            }
            set
            {
                OnNickNameChanging(value);
                ReportPropertyChanging("NickName");
                _NickName = StructuralObject.SetValidValue(value, false, "NickName");
                ReportPropertyChanged("NickName");
                OnNickNameChanged();
            }
        }
        private global::System.String _NickName;
        partial void OnNickNameChanging(global::System.String value);
        partial void OnNickNameChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Affiliation
        {
            get
            {
                return _Affiliation;
            }
            set
            {
                OnAffiliationChanging(value);
                ReportPropertyChanging("Affiliation");
                _Affiliation = StructuralObject.SetValidValue(value, true, "Affiliation");
                ReportPropertyChanged("Affiliation");
                OnAffiliationChanged();
            }
        }
        private global::System.String _Affiliation;
        partial void OnAffiliationChanging(global::System.String value);
        partial void OnAffiliationChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Detail
        {
            get
            {
                return _Detail;
            }
            set
            {
                OnDetailChanging(value);
                ReportPropertyChanging("Detail");
                _Detail = StructuralObject.SetValidValue(value, true, "Detail");
                ReportPropertyChanged("Detail");
                OnDetailChanged();
            }
        }
        private global::System.String _Detail;
        partial void OnDetailChanging(global::System.String value);
        partial void OnDetailChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MailAddress
        {
            get
            {
                return _MailAddress;
            }
            set
            {
                OnMailAddressChanging(value);
                ReportPropertyChanging("MailAddress");
                _MailAddress = StructuralObject.SetValidValue(value, true, "MailAddress");
                ReportPropertyChanged("MailAddress");
                OnMailAddressChanged();
            }
        }
        private global::System.String _MailAddress;
        partial void OnMailAddressChanging(global::System.String value);
        partial void OnMailAddressChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CellPhoneNum
        {
            get
            {
                return _CellPhoneNum;
            }
            set
            {
                OnCellPhoneNumChanging(value);
                ReportPropertyChanging("CellPhoneNum");
                _CellPhoneNum = StructuralObject.SetValidValue(value, true, "CellPhoneNum");
                ReportPropertyChanged("CellPhoneNum");
                OnCellPhoneNumChanged();
            }
        }
        private global::System.String _CellPhoneNum;
        partial void OnCellPhoneNumChanging(global::System.String value);
        partial void OnCellPhoneNumChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNum
        {
            get
            {
                return _PhoneNum;
            }
            set
            {
                OnPhoneNumChanging(value);
                ReportPropertyChanging("PhoneNum");
                _PhoneNum = StructuralObject.SetValidValue(value, true, "PhoneNum");
                ReportPropertyChanged("PhoneNum");
                OnPhoneNumChanged();
            }
        }
        private global::System.String _PhoneNum;
        partial void OnPhoneNumChanging(global::System.String value);
        partial void OnPhoneNumChanged();

        #endregion

        #region ナビゲーション プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sample01RModel", "ModuleUser", "Module")]
        public EntityCollection<Module> Modules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Module>("Sample01RModel.ModuleUser", "Module");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Module>("Sample01RModel.ModuleUser", "Module", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
