//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.Modules = new HashSet<Module>();
        }
    
        public int id { get; set; }
        public string Unit1 { get; set; }
        public int TypeDataId { get; set; }
    
        public virtual ICollection<Module> Modules { get; set; }
    }
}
